name: checkout-project-repository
run-name: Checkout on Project Repository

on:
  - push

jobs:
  checkout-and-list-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a

      # 1) Checkout da aplicação - Via manual (utilizando variáveis do GitHub)
      # - name: Checkout
      #   run: |
      #     git init
      #     git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
      #     git fetch origin
      #     git checkout master

      # 2) Checkout da aplicação - Via Action do GitHub (script automatizado)
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files after
        run: ls -a