name: events-and-filters
run-name: Repository Events and Filters

on:
  pull_request: # No evento de criação de um Pull Request
    branches: # Filtro: Para a branch de destino "master" 
      - "master"
    paths: # Filtro: Que houver alteração em qualquer arquivo JS a partir da raiz
      - "**.js"

jobs:
  show-ref-and-sha:
    runs-on: ubuntu-latest
    steps:
      - name: Echo GITHUB_SHA and GITHUB_REF # Exibe o SHA do último commit e o nome da branch temporária de merge do Pull Request
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF